lz4: Rename `current` variable to `currentPos`
Compiler gets confused between current variable in lz4.c and the
current macro in current.h.

This fixes the following compilation errors:

../lib/lz4/lz4.c:1145:15: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
 1145 |                                 U32 const current = (U32)(forwardIp - base);
      |                                           ^
../arch/arm64/include/asm/current.h:24:28: note: expanded from macro 'current'
   24 | #define current get_current()
      |                            ^
../lib/lz4/lz4.c:1145:15: error: conflicting types for 'get_current'
../arch/arm64/include/asm/current.h:24:17: note: expanded from macro 'current'
   24 | #define current get_current()
      |                 ^
../arch/arm64/include/asm/current.h:15:44: note: previous definition is here
   15 | static __always_inline struct task_struct *get_current(void)
      |                                            ^
../lib/lz4/lz4.c:1145:15: error: illegal initializer (only variables can be initialized)
 1145 |                                 U32 const current = (U32)(forwardIp - base);
      |                                           ^
../arch/arm64/include/asm/current.h:24:17: note: expanded from macro 'current'
   24 | #define current get_current()
      |                 ^

Change-Id: c80e91524283315c3cec00d0221488083c113a2a
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: TogoFire <togofire@mailfence.com>
(cherry picked from commit 738eb8a04b855102879dc65f95bbb2c245e2e855)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>