techpack: display: display -> dsi_display
Changed by upstream commit.

/home/x0x00044/ROM/LineageOS/kernel/nothing/sm7325/techpack/display/msm/sde/sde_connector.c:146:2: error: use of undeclared identifier 'display'
        display->panel->bl_config.real_bl_level = bl_lvl;
        ^
/home/x0x00044/ROM/LineageOS/kernel/nothing/sm7325/techpack/display/msm/sde/sde_connector.c:150:12: error: use of undeclared identifier 'display'
                bl_lvl = display->panel->bl_config.bl_hbm_level;

Change-Id: I4c181d62bfd7af8c562ee9fcb84719b664efb6e3